version: v7.0.2-{branch}-{build}

environment:
  matrix:
  - QTDIR: C:\Qt\5.5\msvc2013_64
    CMAKE_GENERATOR: Visual Studio 12 Win64
  - QTDIR: C:\Qt\5.5\msvc2013
    CMAKE_GENERATOR: Visual Studio 12

install:
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - cmake -G "%CMAKE_GENERATOR%" .
  - cmake --build .

test: off
