language: cpp

sudo: false
dist: trusty

matrix:
  include:
  - os: linux
    env: QT_VERSION=qt4
    compiler: clang
    addons:
      apt:
        packages:
          - libqt4-dev
  - os: linux
    env: QT_VERSION=qt4
    compiler: gcc
    addons:
      apt:
        packages:
          - libqt4-dev
  - os: linux
    env: QT_VERSION=qt5 TRAVIS_DEPLOY=y
    compiler: clang
    addons:
      apt:
        packages:
          - qtbase5-dev
  - os: linux
    env: QT_VERSION=qt5
    compiler: gcc
    addons:
      apt:
        packages:
          - qtbase5-dev
  - os: osx
    env: QT_VERSION=qt5
    compiler: clang


install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install qt; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi
- if [[ "$QT_VERSION"     == "qt4" ]]; then CMAKE_ARGS="-DWITH_QT4=ON"; fi
- mkdir build && cd build && cmake $CMAKE_ARGS .. && make package

deploy:
  provider: releases
  api_key:
    secure: K/oQcA724SgW+vOObh7DSLowDZtdlGD/fKvmyXPfMC35uQn9qsne1LEeNhtyCRDKSnTw1thnksx60qzPzVWg2sRdNl2YGL+yQlM82i1kqkzfCbRE4TI7FS9bDV2M1yMCA7n6f/1kYFfcbTINFdJjg274YVZiZK+IrTqeb+c9zBwGhrSYtD0USW+h0DqwONs2vq1IhnnFgTfQx+46VxkxA+3wVS4wk5snMsb+sLZ2wZLKExDzo2WY9iBrkKLs860WKM0INdvZiWQnNMUftJ67U0gUIKP5O5OI1N+Lu+dloZnT3Sih0yvcFF0JLZzYYVSPK0EP6aW4+/L28R8NBeKUC7H7CQFXpG92eKZHlyPvC7lX91lr8Vu3fShVK78AONM7bIZExg2Hit6sD+qo8+lH7E+YazWo1Pad1+NKfUp4FUmi2pWxyAGH6uh3yA/eYQJ7/2fX9u3M98D4qAXKZlr82XAwAr8M3MmOemeOV9/03dR6FsP5JhZjlhsVE3Tcc0T0vNEwMMIWx9KxgOPo3Ul+wHVOKJv6eEMg0z7eazn5YT2yWv3hRhVSxVglLLcfxHdiPQ/IdmVz1gAIuRPfUtkeQqDsc5bF5fXHd3Pt90t9slzYXn92ItMkHEjfjdD8FgKtur+HZ98HtskPUzuq37Rs0r81UKAwmkSuDMnjuQkds+M=
  skip_cleanup: true
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/build/libcbsdk_*.deb"
  on:
    tags: true
    condition: "$TRAVIS_DEPLOY = y"
